name: Deploy VuePress to GitHub Pages

on:
  push:
    branches:
      - main  # 你的默认分支，如果是 master 就改成 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 或根据你的需要设置为其他版本

      - name: Install dependencies
        run: npm install

      - name: Build VuePress
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
